services:
  - type: web
    name: vpn-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python vpn_bot/bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8415084076:AAFUuWgyOGXK3aFv5zp9ILwMRKSdcV8TtYI
